import type {
  ArchitectureSpec,
  LayerSet,
  OriArchAdapter,
  RootConfig,
} from "@ori-ori/parser";

interface RustMatcher {
  layerId: string;
  kind: "shared" | "feature" | "ui-layer";
  prefix: string;
  feature: boolean;
}

interface RustRule {
  from: string;
  allow: string[];
}

function ensureTrailingSlash(p: string): string {
  return p.endsWith("/") ? p : `${p}/`;
}

function featureBase(root: RootConfig): string {
  return root.feature_root === "."
    ? ensureTrailingSlash(root.path)
    : ensureTrailingSlash(`${root.path}/${root.feature_root}`);
}

function buildMatchers(set: LayerSet, root: RootConfig): RustMatcher[] {
  const featBase = featureBase(root);
  const matchers: RustMatcher[] = [];
  for (const layer of set.layers) {
    if (layer.kind === "shared") {
      matchers.push({
        layerId: layer.id,
        kind: "shared",
        prefix: `${featBase}${layer.id}/`,
        feature: false,
      });
    } else if (layer.kind === "ui-layer") {
      matchers.push({
        layerId: layer.id,
        kind: "ui-layer",
        prefix: `${root.path}/${layer.id}/`,
        feature: false,
      });
    }
  }
  for (const layer of set.layers) {
    if (layer.kind === "feature") {
      matchers.push({
        layerId: layer.id,
        kind: "feature",
        prefix: featBase,
        feature: true,
      });
    }
  }
  return matchers;
}

function crateRoot(root: RootConfig): string {
  // Cargo convention: integration tests live at <crate-root>/tests/.
  // For root.path="src-tauri/src" the crate root is "src-tauri";
  // for root.path="src" it's "." (project root).
  if (root.path === "src") return ".";
  if (root.path.endsWith("/src")) {
    return root.path.slice(0, -"/src".length);
  }
  return root.path;
}

function escapeRustStr(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function emitMatchers(matchers: RustMatcher[]): string {
  const lines = matchers.map(
    (m) =>
      `    LayerMatcher { layer_id: "${escapeRustStr(m.layerId)}", kind: "${m.kind}", prefix: "${escapeRustStr(m.prefix)}", feature: ${m.feature} },`,
  );
  return lines.join("\n");
}

function emitRules(rules: RustRule[]): string {
  const lines = rules.map((r) => {
    const allow = r.allow.map((a) => `"${escapeRustStr(a)}"`).join(", ");
    return `    ("${escapeRustStr(r.from)}", &[${allow}]),`;
  });
  return lines.join("\n");
}

function renderArchTest(
  spec: ArchitectureSpec,
  root: RootConfig,
  matchers: RustMatcher[],
  rules: RustRule[],
): string {
  const featBase = featureBase(root);
  return `//! AUTO-GENERATED by @ori-ori/arch-adapter-rust — do not edit.
//! Regenerate with: ori arch export --adapter=rust
//! Source: .ori/architecture.md (root id: ${escapeRustStr(root.id)})

use std::fs;
use std::path::{Path, PathBuf};

const ROOT_PATH: &str = "${escapeRustStr(root.path)}";
const FEATURE_BASE: &str = "${escapeRustStr(featBase)}";
const PUBLIC_ENTRY: &str = "${escapeRustStr(root.public_entry)}";
const CROSS_FEATURE_PROHIBITED: bool = ${spec.cross_feature.prohibited_direct ? "true" : "false"};

struct LayerMatcher {
    layer_id: &'static str,
    kind: &'static str,
    prefix: &'static str,
    feature: bool,
}

const MATCHERS: &[LayerMatcher] = &[
${emitMatchers(matchers)}
];

const CROSS_LAYER_RULES: &[(&str, &[&str])] = &[
${emitRules(rules)}
];

#[derive(Debug, Clone)]
struct LayerHit {
    layer_id: &'static str,
    kind: &'static str,
    feature_name: Option<String>,
}

fn classify(rel: &str) -> Option<LayerHit> {
    for m in MATCHERS {
        if rel.starts_with(m.prefix) {
            if m.feature {
                let tail = &rel[m.prefix.len()..];
                let mut segs = tail.split('/').filter(|s| !s.is_empty());
                let first = segs.next()?;
                segs.next()?; // require at least one segment inside the feature folder
                return Some(LayerHit {
                    layer_id: m.layer_id,
                    kind: m.kind,
                    feature_name: Some(first.to_string()),
                });
            }
            return Some(LayerHit {
                layer_id: m.layer_id,
                kind: m.kind,
                feature_name: None,
            });
        }
    }
    None
}

fn walk_rust(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') || name == "target" || name == "node_modules" {
            continue;
        }
        let path = entry.path();
        if path.is_dir() {
            walk_rust(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            out.push(path);
        }
    }
}

fn extract_uses(content: &str) -> Vec<(String, usize)> {
    let mut out = Vec::new();
    for (i, line) in content.lines().enumerate() {
        let trimmed = line.trim_start();
        let rest = trimmed
            .strip_prefix("pub use ")
            .or_else(|| trimmed.strip_prefix("use "));
        if let Some(rest) = rest {
            let end = rest
                .find(|c: char| c == ';' || c == '{' || c == ' ')
                .unwrap_or(rest.len());
            let head = rest[..end].trim().trim_end_matches("::");
            if !head.is_empty() {
                out.push((head.to_string(), i + 1));
            }
        }
    }
    out
}

fn module_dir(importer: &Path) -> Option<PathBuf> {
    // Rust 2018+ module-file rule:
    //   <dir>/mod.rs        defines module <dir>
    //   <dir>/<name>.rs     defines module <name> nested under <dir>
    // The directory of the *importer module* is therefore:
    //   for mod.rs           → importer.parent()        (current dir IS the module dir)
    //   for any other file   → importer.parent().join(<name>)  conceptually,
    //                          but its file siblings live in importer.parent() itself.
    // We return the dir that holds sibling files reachable via self::*.
    let parent = importer.parent()?;
    if importer.file_name().and_then(|s| s.to_str()) == Some("mod.rs") {
        Some(parent.to_path_buf())
    } else {
        Some(parent.to_path_buf())
    }
}

fn parent_module_dir(importer: &Path) -> Option<PathBuf> {
    // The dir reached by super::* — one module up from the importer.
    //   for <dir>/mod.rs     → <dir>'s parent
    //   for <dir>/<name>.rs  → <dir> itself (because <name>'s parent module is <dir>)
    let parent = importer.parent()?;
    if importer.file_name().and_then(|s| s.to_str()) == Some("mod.rs") {
        parent.parent().map(Path::to_path_buf)
    } else {
        Some(parent.to_path_buf())
    }
}

fn resolve_use(target: &str, importer: &Path) -> Option<PathBuf> {
    if let Some(rest) = target.strip_prefix("crate::") {
        let mut p = PathBuf::from(ROOT_PATH);
        for s in rest.split("::").filter(|s| !s.is_empty()) {
            p.push(s);
        }
        p.set_extension("rs");
        return Some(p);
    }
    if let Some(rest) = target.strip_prefix("super::") {
        let mut p = parent_module_dir(importer)?;
        for s in rest.split("::").filter(|s| !s.is_empty()) {
            p.push(s);
        }
        p.set_extension("rs");
        return Some(p);
    }
    if let Some(rest) = target.strip_prefix("self::") {
        let mut p = module_dir(importer)?;
        for s in rest.split("::").filter(|s| !s.is_empty()) {
            p.push(s);
        }
        p.set_extension("rs");
        return Some(p);
    }
    None
}

fn check_pair(importer: &LayerHit, target: &LayerHit) -> Result<(), String> {
    if importer.layer_id == target.layer_id
        && importer.kind == "feature"
        && importer.feature_name.is_some()
        && importer.feature_name == target.feature_name
    {
        return Ok(()); // same feature — governed by feature_internal (not enforced here)
    }

    if CROSS_FEATURE_PROHIBITED
        && importer.layer_id == target.layer_id
        && importer.kind == "feature"
        && importer.feature_name != target.feature_name
    {
        return Err(format!(
            "cross-feature direct import: {} → {}",
            importer.feature_name.as_deref().unwrap_or("?"),
            target.feature_name.as_deref().unwrap_or("?"),
        ));
    }

    for (from, allow) in CROSS_LAYER_RULES {
        if *from == importer.layer_id {
            if allow.contains(&target.layer_id) {
                return Ok(());
            }
            return Err(format!(
                "cross-layer: {} → {} not in allow-list [{}]",
                importer.layer_id,
                target.layer_id,
                allow.join(", "),
            ));
        }
    }
    Err(format!("no cross_layer rule for from=\\"{}\\"", importer.layer_id))
}

#[test]
fn architecture_rules() {
    eprintln!("ori arch: scanning {} (public_entry={})", ROOT_PATH, PUBLIC_ENTRY);
    eprintln!("ori arch: feature_base={}", FEATURE_BASE);

    let mut files = Vec::new();
    walk_rust(Path::new(ROOT_PATH), &mut files);

    let mut violations: Vec<String> = Vec::new();
    for file in &files {
        let rel = file.to_string_lossy().replace('\\\\', "/");
        let importer = match classify(&rel) {
            Some(h) => h,
            None => continue,
        };
        let content = match fs::read_to_string(file) {
            Ok(c) => c,
            Err(_) => continue,
        };
        for (target, line) in extract_uses(&content) {
            let resolved = match resolve_use(&target, file) {
                Some(r) => r,
                None => continue,
            };
            let rel_target = resolved.to_string_lossy().replace('\\\\', "/");
            let target_hit = match classify(&rel_target) {
                Some(h) => h,
                None => continue,
            };
            if let Err(reason) = check_pair(&importer, &target_hit) {
                violations.push(format!(
                    "{}:{}: use {} ({}): {}",
                    rel,
                    line,
                    target,
                    target_hit.layer_id,
                    reason,
                ));
            }
        }
    }

    if !violations.is_empty() {
        panic!(
            "ori arch: {} violation(s):\\n  {}\\n",
            violations.len(),
            violations.join("\\n  "),
        );
    }
}
`;
}

const adapter: OriArchAdapter = {
  name: "rust",
  language: "rust",

  async export(spec, root) {
    if (root.language !== "rust") {
      return {
        files: [],
        notes: [
          `rust adapter skipped: root "${root.id}" is language=${root.language}, not rust.`,
        ],
      };
    }
    const set = spec.layer_sets[root.layer_set];
    if (!set) {
      throw new Error(`layer_set "${root.layer_set}" not found in layer_sets`);
    }

    const matchers = buildMatchers(set, root);
    const rules: RustRule[] = set.rules.cross_layer.map((cr) => ({
      from: cr.from,
      allow: [...cr.allow],
    }));

    const content = renderArchTest(spec, root, matchers, rules);
    const path = `${crateRoot(root)}/tests/arch.rs`;

    return {
      files: [{ path, content }],
      notes: [
        `Run \`cargo test --test arch\` from ${crateRoot(root)} to verify architecture rules.`,
        "The generated test is self-contained (no extra crates). It walks .rs files and panics on violation.",
      ],
    };
  },
};

export default adapter;
