import { describe, expect, it } from "vitest";
import { parseArchitectureSpec } from "@ori-ori/parser";
import adapter from "./index.js";

const SINGLE_CRATE_SPEC = `---
version: 1
root:
  path: src
  language: rust
  layer_set: feature-sliced-rs
  adapter: rust
  slice_root: .
  public_entry: mod.rs
layer_sets:
  feature-sliced-rs:
    layers:
      - { id: shared, kind: shared }
      - { id: domain, kind: slice }
    rules:
      cross_layer:
        - { from: domain, allow: [shared] }
        - { from: shared, allow: [] }
      same_layer: prohibited
      public_entry_required: true
cross_slice:
  prohibited_direct: true
  via: [shared/contracts]
---
`;

const TAURI_SPEC = `---
version: 1
roots:
  - id: ts
    path: src
    language: typescript
    layer_set: feature-sliced-ts
    adapter: eslint
    slice_root: lib
    public_entry: index.ts
  - id: rs
    path: src-tauri/src
    language: rust
    layer_set: feature-sliced-rs
    adapter: rust
    slice_root: .
    public_entry: mod.rs
layer_sets:
  feature-sliced-ts:
    layers: [{ id: shared, kind: shared }]
    rules: { cross_layer: [], same_layer: prohibited, public_entry_required: true }
  feature-sliced-rs:
    layers:
      - { id: shared, kind: shared }
      - { id: domain, kind: slice }
    rules:
      cross_layer:
        - { from: domain, allow: [shared] }
        - { from: shared, allow: [] }
      same_layer: prohibited
      public_entry_required: true
cross_slice:
  prohibited_direct: true
  via: [shared/contracts]
---
`;

describe("@ori-ori/arch-adapter-rust", () => {
  it("declares the adapter contract", () => {
    expect(adapter.name).toBe("rust");
    expect(adapter.language).toBe("rust");
  });

  it("emits tests/arch.rs for a single-crate project", async () => {
    const spec = parseArchitectureSpec(SINGLE_CRATE_SPEC);
    const result = await adapter.export(spec, spec.roots[0]!);

    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.path).toBe("./tests/arch.rs");
    const content = result.files[0]!.content;
    expect(content).toContain("AUTO-GENERATED by @ori-ori/arch-adapter-rust");
    expect(content).toContain("#[test]");
    expect(content).toContain("fn architecture_rules()");
    expect(content).toContain("const ROOT_PATH: &str = \"src\"");
  });

  it("places the test file under <crate-root>/tests/ for a Tauri layout", async () => {
    const spec = parseArchitectureSpec(TAURI_SPEC);
    const rsRoot = spec.roots.find((r) => r.id === "rs")!;
    const result = await adapter.export(spec, rsRoot);

    expect(result.files[0]?.path).toBe("src-tauri/tests/arch.rs");
    expect(result.files[0]!.content).toContain("const ROOT_PATH: &str = \"src-tauri/src\"");
  });

  it("encodes slice matchers with slice: true", async () => {
    const spec = parseArchitectureSpec(SINGLE_CRATE_SPEC);
    const result = await adapter.export(spec, spec.roots[0]!);
    const content = result.files[0]!.content;

    // shared matcher first, then domain slice matcher with slice: true
    expect(content).toMatch(/layer_id: "shared"[\s\S]*slice: false/);
    expect(content).toMatch(/layer_id: "domain"[\s\S]*slice: true/);

    const sharedIdx = content.indexOf('layer_id: "shared"');
    const domainIdx = content.indexOf('layer_id: "domain"');
    expect(sharedIdx).toBeGreaterThan(0);
    expect(domainIdx).toBeGreaterThan(sharedIdx);
  });

  it("encodes cross-layer rules from the spec", async () => {
    const spec = parseArchitectureSpec(SINGLE_CRATE_SPEC);
    const result = await adapter.export(spec, spec.roots[0]!);
    const content = result.files[0]!.content;

    expect(content).toContain('("domain", &["shared"])');
    expect(content).toContain('("shared", &[])');
  });

  it("skips non-rust roots with a note", async () => {
    const spec = parseArchitectureSpec(TAURI_SPEC);
    const tsRoot = spec.roots.find((r) => r.id === "ts")!;
    const result = await adapter.export(spec, tsRoot);

    expect(result.files).toHaveLength(0);
    expect(result.notes?.join("\n")).toMatch(/skipped/);
  });

  it("emits the mod.rs-aware super:: resolver (regression for ori-w5j)", async () => {
    const spec = parseArchitectureSpec(SINGLE_CRATE_SPEC);
    const result = await adapter.export(spec, spec.roots[0]!);
    const content = result.files[0]!.content;

    // The fix introduces parent_module_dir() / module_dir() helpers that
    // branch on whether the importer file is `mod.rs`. Without this branch,
    // `super::X` from a non-mod.rs sibling would walk one dir too far up
    // and mis-classify intra-slice imports as cross-slice violations.
    expect(content).toContain("fn parent_module_dir(importer: &Path)");
    expect(content).toContain("fn module_dir(importer: &Path)");
    expect(content).toContain('importer.file_name().and_then(|s| s.to_str()) == Some("mod.rs")');

    // super:: resolver must use parent_module_dir, not the old
    // importer.parent()?.parent()? double-pop.
    expect(content).toMatch(
      /target\.strip_prefix\("super::"\)[\s\S]*?parent_module_dir\(importer\)/,
    );
    expect(content).not.toMatch(
      /target\.strip_prefix\("super::"\)[\s\S]*?importer\.parent\(\)\?\.parent\(\)\?/,
    );
  });
});
