import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  applyUiLayerSection,
  collectUiFeatures,
  DEFAULT_MARKER,
  parseScreen,
  renderUiLayerSection,
  syncUiLayer,
  SyncUiLayerError,
} from "./sync-ui.js";

const ARCH_BASE = `---
version: 1
root:
  path: src
  language: typescript
  layer_set: feature-sliced-ts
  adapter: eslint
  feature_root: lib
  public_entry: index.ts
layer_sets:
  feature-sliced-ts:
    layers:
      - { id: shared, kind: shared }
      - { id: domain, kind: feature, feature_internal: feature-internal-ts }
    rules:
      cross_layer:
        - { from: domain, allow: [shared] }
        - { from: shared, allow: [] }
      same_layer: prohibited
      public_entry_required: true
feature_internal:
  feature-internal-ts:
    sub_layers: [presentation, application, domain, infrastructure]
    rules:
      - { from: presentation, allow: [application, domain] }
      - { from: application,  allow: [domain, infrastructure] }
      - { from: domain,       allow: [] }
      - { from: infrastructure, allow: [domain] }
cross_feature:
  prohibited_direct: true
  via: [shared/contracts, shared/events]
---

# Architecture

User-written prose stays here.
`;

const SCREEN_1 = `---
coherence:
  source: human
  last_validated: 2026-05-14
  upstream:
    - workflows/capture-auto-save.md
  depended_by:
    - ui-feature: ui-capture-form
---

# Screen 1: Capture {#screen-1}
`;

const SCREEN_2 = `---
coherence:
  depended_by:
    - ui-feature: ui-note-browser
  depends_on:
    - screen: screen-3
---

# Screen 2: Edit {#screen-2}
`;

const SCREEN_3 = `---
coherence:
  depended_by:
    - ui-feature: ui-note-browser
---

# Screen 3: List {#screen-3}
`;

const SCREEN_NO_BINDING = `---
coherence:
  source: human
---

# Screen 4: Unbound {#screen-4}
`;

describe("parseScreen", () => {
  it("extracts a single ui-feature binding", () => {
    const s = parseScreen("screen-1.md", SCREEN_1);
    expect(s).not.toBeNull();
    expect(s?.screenId).toBe("screen-1");
    expect(s?.uiFeatures).toEqual(["ui-capture-form"]);
  });

  it("records depends_on screens when present", () => {
    const s = parseScreen("screen-2.md", SCREEN_2);
    expect(s?.dependsOnScreens).toEqual(["screen-3"]);
  });

  it("returns empty bindings when the frontmatter has no depended_by", () => {
    const s = parseScreen("screen-4.md", SCREEN_NO_BINDING);
    expect(s?.uiFeatures).toEqual([]);
  });

  it("rejects files that don't match the screen-*.md convention", () => {
    expect(parseScreen("index.md", SCREEN_1)).toBeNull();
  });
});

describe("collectUiFeatures", () => {
  it("groups screens under their ui-feature, sorted by feature id then screen number", () => {
    const screens = [
      parseScreen("screen-1.md", SCREEN_1)!,
      parseScreen("screen-2.md", SCREEN_2)!,
      parseScreen("screen-3.md", SCREEN_3)!,
    ];
    const features = collectUiFeatures(screens);
    expect(features.map((f) => f.id)).toEqual(["ui-capture-form", "ui-note-browser"]);
    expect(features[1]?.screens).toEqual(["screen-2", "screen-3"]);
  });
});

describe("renderUiLayerSection / applyUiLayerSection", () => {
  it("emits an empty-state hint when no features were derived", () => {
    const body = renderUiLayerSection([]);
    expect(body).toContain("No `ui-feature` bindings");
    expect(body).toContain("/ori-ddd-11b-ui-grouping");
  });

  it("renders one block per feature with screens and sources", () => {
    const features = collectUiFeatures([
      parseScreen("screen-1.md", SCREEN_1)!,
      parseScreen("screen-2.md", SCREEN_2)!,
      parseScreen("screen-3.md", SCREEN_3)!,
    ]);
    const body = renderUiLayerSection(features);
    expect(body).toContain("### ui-capture-form");
    expect(body).toContain("Screens: screen-1");
    expect(body).toContain("### ui-note-browser");
    expect(body).toContain("Screens: screen-2, screen-3");
  });

  it("appends a marker block to a spec that has none", () => {
    const next = applyUiLayerSection(ARCH_BASE, "## hello\n");
    expect(next).toContain(`<!-- ${DEFAULT_MARKER}:begin -->`);
    expect(next).toContain(`<!-- ${DEFAULT_MARKER}:end -->`);
    expect(next).toContain("AUTO-GENERATED by");
    // Original prose preserved.
    expect(next).toContain("User-written prose stays here.");
  });

  it("replaces an existing marker block in place", () => {
    const seeded = applyUiLayerSection(ARCH_BASE, "## first\n");
    const next = applyUiLayerSection(seeded, "## second\n");
    expect(next).toContain("## second");
    expect(next).not.toContain("## first");
    // Only one pair of markers.
    expect(next.match(new RegExp(`${DEFAULT_MARKER}:begin`, "g"))?.length).toBe(1);
  });
});

describe("syncUiLayer (filesystem)", () => {
  let tmp: string;

  beforeEach(async () => {
    tmp = await mkdtemp(join(tmpdir(), "ori-sync-ui-"));
    await mkdir(join(tmp, ".ori/domain/ui-fields"), { recursive: true });
    await writeFile(join(tmp, ".ori/architecture.md"), ARCH_BASE, "utf8");
  });

  afterEach(async () => {
    await rm(tmp, { recursive: true, force: true });
  });

  it("writes a UI feature manifest section derived from screen files", async () => {
    await writeFile(join(tmp, ".ori/domain/ui-fields/screen-1.md"), SCREEN_1, "utf8");
    await writeFile(join(tmp, ".ori/domain/ui-fields/screen-2.md"), SCREEN_2, "utf8");
    await writeFile(join(tmp, ".ori/domain/ui-fields/screen-3.md"), SCREEN_3, "utf8");

    const result = await syncUiLayer({ cwd: tmp });
    expect(result.changed).toBe(true);
    expect(result.screensRead).toBe(3);
    expect(result.features.map((f) => f.id)).toEqual(["ui-capture-form", "ui-note-browser"]);

    const written = await readFile(join(tmp, ".ori/architecture.md"), "utf8");
    expect(written).toContain("### ui-capture-form");
    expect(written).toContain("### ui-note-browser");
    expect(written).toContain("User-written prose stays here.");
  });

  it("is idempotent: a second run on identical inputs reports no change", async () => {
    await writeFile(join(tmp, ".ori/domain/ui-fields/screen-1.md"), SCREEN_1, "utf8");
    await syncUiLayer({ cwd: tmp });
    const second = await syncUiLayer({ cwd: tmp });
    expect(second.changed).toBe(false);
  });

  it("does not write when dry-run is on, but reports the computed content", async () => {
    await writeFile(join(tmp, ".ori/domain/ui-fields/screen-1.md"), SCREEN_1, "utf8");
    const result = await syncUiLayer({ cwd: tmp, dryRun: true });
    expect(result.changed).toBe(true);
    const onDisk = await readFile(join(tmp, ".ori/architecture.md"), "utf8");
    expect(onDisk).not.toContain("ui-capture-form");
    expect(result.nextContent).toContain("ui-capture-form");
  });

  it("preserves manual edits outside the marker block on subsequent syncs", async () => {
    await writeFile(join(tmp, ".ori/domain/ui-fields/screen-1.md"), SCREEN_1, "utf8");
    await syncUiLayer({ cwd: tmp });

    const seeded = await readFile(join(tmp, ".ori/architecture.md"), "utf8");
    const edited = `${seeded}\n## My Manual Notes\n\nKeep this on the next sync.\n`;
    await writeFile(join(tmp, ".ori/architecture.md"), edited, "utf8");

    await writeFile(
      join(tmp, ".ori/domain/ui-fields/screen-3.md"),
      SCREEN_3,
      "utf8",
    );
    await syncUiLayer({ cwd: tmp });

    const after = await readFile(join(tmp, ".ori/architecture.md"), "utf8");
    expect(after).toContain("Keep this on the next sync.");
    expect(after).toContain("### ui-note-browser");
  });

  it("errors out cleanly when the architecture spec is missing", async () => {
    await rm(join(tmp, ".ori/architecture.md"));
    await expect(syncUiLayer({ cwd: tmp })).rejects.toBeInstanceOf(SyncUiLayerError);
  });

  it("errors out cleanly when the ui-fields directory is missing", async () => {
    await rm(join(tmp, ".ori/domain/ui-fields"), { recursive: true });
    await expect(syncUiLayer({ cwd: tmp })).rejects.toBeInstanceOf(SyncUiLayerError);
  });
});
