// Auto-derive the UI feature manifest section of .ori/architecture.md from
// the depended_by frontmatter of .ori/domain/ui-fields/screen-*.md, the
// output of ori-ddd-11b. The generated section lives between marker
// comments so manual prose elsewhere in architecture.md is preserved.

import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { parseFrontmatter } from "@ori-ori/parser";

export const DEFAULT_MARKER = "ori:ui-layer";
const SCREEN_PREFIX = "screen-";
const SCREEN_SUFFIX = ".md";
const ARCHITECTURE_PATH = ".ori/architecture.md";
const UI_FIELDS_DIR = ".ori/domain/ui-fields";

export interface ScreenBinding {
  readonly screenId: string;
  readonly file: string;
  readonly uiFeatures: readonly string[];
  readonly dependsOnScreens: readonly string[];
}

export interface UiFeatureEntry {
  readonly id: string;
  readonly screens: readonly string[];
  readonly sources: readonly string[];
}

interface CoherenceMap {
  depended_by?: unknown;
  depends_on?: unknown;
}

interface FrontmatterShape {
  coherence?: CoherenceMap;
}

function extractFeatureIds(value: unknown, key: string): string[] {
  if (!Array.isArray(value)) return [];
  const ids: string[] = [];
  for (const entry of value) {
    if (typeof entry === "object" && entry !== null && !Array.isArray(entry)) {
      const rec = entry as Record<string, unknown>;
      const raw = rec[key];
      if (typeof raw === "string" && raw.length > 0) ids.push(raw);
    }
  }
  return ids;
}

export function parseScreen(file: string, raw: string): ScreenBinding | null {
  const screenId = basename(file, SCREEN_SUFFIX);
  if (!screenId.startsWith(SCREEN_PREFIX)) return null;
  const { data } = parseFrontmatter(raw);
  const fm = data as FrontmatterShape;
  const coherence = fm.coherence ?? {};
  return {
    screenId,
    file,
    uiFeatures: extractFeatureIds(coherence.depended_by, "ui-feature"),
    dependsOnScreens: extractFeatureIds(coherence.depends_on, "screen"),
  };
}

function compareScreenIds(a: string, b: string): number {
  // screen-1, screen-2, ... screen-10 — numeric where possible, fall back to string.
  const an = Number(a.slice(SCREEN_PREFIX.length));
  const bn = Number(b.slice(SCREEN_PREFIX.length));
  if (Number.isFinite(an) && Number.isFinite(bn)) return an - bn;
  return a.localeCompare(b);
}

export function collectUiFeatures(screens: readonly ScreenBinding[]): UiFeatureEntry[] {
  const byFeature = new Map<string, { screens: Set<string>; sources: Set<string> }>();
  for (const s of screens) {
    for (const feature of s.uiFeatures) {
      let agg = byFeature.get(feature);
      if (!agg) {
        agg = { screens: new Set(), sources: new Set() };
        byFeature.set(feature, agg);
      }
      agg.screens.add(s.screenId);
      agg.sources.add(s.file);
    }
  }
  const features: UiFeatureEntry[] = [];
  for (const [id, agg] of byFeature) {
    features.push({
      id,
      screens: [...agg.screens].sort(compareScreenIds),
      sources: [...agg.sources].sort(),
    });
  }
  features.sort((a, b) => a.id.localeCompare(b.id));
  return features;
}

export function renderUiLayerSection(features: readonly UiFeatureEntry[]): string {
  const lines: string[] = [];
  lines.push("## UI Features (auto-derived from `.ori/domain/ui-fields/`)");
  lines.push("");
  if (features.length === 0) {
    lines.push("_No `ui-feature` bindings found in `screen-*.md` frontmatter yet._");
    lines.push("");
    lines.push("Run `/ori-ddd-11b-ui-grouping` to assign each screen to a UI feature.");
    return `${lines.join("\n")}\n`;
  }
  for (const f of features) {
    lines.push(`### ${f.id}`);
    lines.push("");
    lines.push(`- Screens: ${f.screens.join(", ")}`);
    lines.push(`- Sources: ${f.sources.map((s) => `\`${s}\``).join(", ")}`);
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function buildDelimiters(marker: string): { begin: string; end: string } {
  return {
    begin: `<!-- ${marker}:begin -->`,
    end: `<!-- ${marker}:end -->`,
  };
}

const NOTICE =
  "<!-- AUTO-GENERATED by `ori arch sync-ui`. Edits between the marker comments\n     will be overwritten on the next sync. Manual prose outside is preserved. -->";

export function applyUiLayerSection(
  archMd: string,
  body: string,
  marker: string = DEFAULT_MARKER,
): string {
  const { begin, end } = buildDelimiters(marker);
  const block = `${begin}\n${NOTICE}\n\n${body.trimEnd()}\n\n${end}`;
  const beginIdx = archMd.indexOf(begin);
  const endIdx = archMd.indexOf(end);
  if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
    const before = archMd.slice(0, beginIdx);
    const after = archMd.slice(endIdx + end.length);
    return `${before}${block}${after}`;
  }
  // Append at end of file with a separating blank line.
  const trimmed = archMd.replace(/\s+$/u, "");
  return `${trimmed}\n\n${block}\n`;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

async function listScreenFiles(uiFieldsDir: string): Promise<string[]> {
  const entries = await readdir(uiFieldsDir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (!entry.name.startsWith(SCREEN_PREFIX)) continue;
    if (!entry.name.endsWith(SCREEN_SUFFIX)) continue;
    files.push(entry.name);
  }
  files.sort(compareScreenIds);
  return files;
}

async function readMarkerFromSpec(specPath: string): Promise<string | null> {
  const raw = await readFile(specPath, "utf8");
  const { data } = parseFrontmatter(raw);
  const fm = data as { page_map_marker?: unknown };
  return typeof fm.page_map_marker === "string" && fm.page_map_marker.length > 0
    ? fm.page_map_marker
    : null;
}

export interface SyncUiLayerOptions {
  readonly cwd: string;
  readonly specPath?: string;
  readonly uiFieldsDir?: string;
  readonly marker?: string;
  readonly dryRun?: boolean;
}

export interface SyncUiLayerResult {
  readonly screensRead: number;
  readonly features: readonly UiFeatureEntry[];
  readonly specPath: string;
  readonly changed: boolean;
  readonly nextContent: string;
}

export class SyncUiLayerError extends Error {
  override readonly name = "SyncUiLayerError";
}

export async function syncUiLayer(opts: SyncUiLayerOptions): Promise<SyncUiLayerResult> {
  const specPath = opts.specPath ?? join(opts.cwd, ARCHITECTURE_PATH);
  const uiFieldsDir = opts.uiFieldsDir ?? join(opts.cwd, UI_FIELDS_DIR);

  if (!(await fileExists(specPath))) {
    throw new SyncUiLayerError(`architecture spec not found: ${specPath}`);
  }
  if (!(await fileExists(uiFieldsDir))) {
    throw new SyncUiLayerError(`ui-fields directory not found: ${uiFieldsDir}`);
  }

  const marker = opts.marker ?? (await readMarkerFromSpec(specPath)) ?? DEFAULT_MARKER;

  const files = await listScreenFiles(uiFieldsDir);
  const screens: ScreenBinding[] = [];
  for (const name of files) {
    const raw = await readFile(join(uiFieldsDir, name), "utf8");
    const parsed = parseScreen(name, raw);
    if (parsed) screens.push(parsed);
  }
  const features = collectUiFeatures(screens);
  const body = renderUiLayerSection(features);

  const current = await readFile(specPath, "utf8");
  const next = applyUiLayerSection(current, body, marker);
  const changed = next !== current;
  if (changed && !opts.dryRun) {
    await writeFile(specPath, next, "utf8");
  }

  return {
    screensRead: screens.length,
    features,
    specPath,
    changed,
    nextContent: next,
  };
}
