import { mkdtemp, rm, mkdir, writeFile, readFile, access } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { bootstrapTauriProject, type TauriRunner } from "./tauri-bootstrap.js";

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

describe("bootstrapTauriProject", () => {
  let tmp: string;
  let calls: { command: string; args: string[]; cwd: string }[];
  const runner: TauriRunner = async (command, args, options) => {
    calls.push({ command, args, cwd: options.cwd });
    return { exitCode: 0, stdout: "", stderr: "" };
  };

  beforeEach(async () => {
    tmp = await mkdtemp(join(tmpdir(), "ori-tauri-bootstrap-"));
    calls = [];
    await mkdir(join(tmp, "src-tauri/src"), { recursive: true });
    await writeFile(
      join(tmp, "src-tauri/src/lib.rs"),
      "// our tauri-specta wiring\nuse tauri_specta::Builder;\n",
      "utf8",
    );
  });

  afterEach(async () => {
    await rm(tmp, { recursive: true, force: true });
  });

  it("invokes pnpm install + pnpm tauri init non-interactively", async () => {
    await bootstrapTauriProject({ cwd: tmp, appName: "my-app", runner });

    expect(calls[0]).toEqual({ command: "pnpm", args: ["install"], cwd: tmp });
    const tauriCall = calls[1]!;
    expect(tauriCall.command).toBe("pnpm");
    expect(tauriCall.args).toContain("tauri");
    expect(tauriCall.args).toContain("init");
    expect(tauriCall.args).toContain("--ci");
    expect(tauriCall.args).toContain("--app-name");
    expect(tauriCall.args).toContain("my-app");
    expect(tauriCall.args).toContain("--directory");
    expect(tauriCall.args).toContain("src-tauri");
    expect(tauriCall.args).toContain("--frontend-dist");
    expect(tauriCall.args).toContain("--dev-url");
  });

  it("restores our lib.rs after tauri init (simulating overwrite)", async () => {
    const overwritingRunner: TauriRunner = async (command, args, options) => {
      calls.push({ command, args, cwd: options.cwd });
      // simulate `tauri init` overwriting lib.rs
      if (args.includes("init")) {
        await writeFile(
          join(options.cwd, "src-tauri/src/lib.rs"),
          "// generated by tauri init",
          "utf8",
        );
      }
      return { exitCode: 0, stdout: "", stderr: "" };
    };

    await bootstrapTauriProject({ cwd: tmp, appName: "my-app", runner: overwritingRunner });

    const restored = await readFile(join(tmp, "src-tauri/src/lib.rs"), "utf8");
    expect(restored).toContain("tauri-specta wiring");
    expect(restored).toContain("tauri_specta::Builder");
  });

  it("can skip the install step", async () => {
    await bootstrapTauriProject({ cwd: tmp, runner, install: false });
    expect(calls.find((c) => c.args[0] === "install")).toBeUndefined();
    expect(calls.find((c) => c.args.includes("init"))).toBeDefined();
  });

  it("sanitizes weird app names into a tauri-safe slug", async () => {
    await bootstrapTauriProject({ cwd: tmp, appName: "My App / v1!", runner });
    const tauriCall = calls[1]!;
    const idx = tauriCall.args.indexOf("--app-name");
    expect(tauriCall.args[idx + 1]).toMatch(/^[a-zA-Z0-9._-]+$/);
  });

  it("throws when a step exits non-zero", async () => {
    const failingRunner: TauriRunner = async () => ({
      exitCode: 1,
      stdout: "",
      stderr: "boom",
    });
    await expect(
      bootstrapTauriProject({ cwd: tmp, runner: failingRunner }),
    ).rejects.toThrow(/exitCode|failed/i);
  });

  it("uses cwd basename as the default app name", async () => {
    await bootstrapTauriProject({ cwd: tmp, runner });
    const tauriCall = calls[1]!;
    const idx = tauriCall.args.indexOf("--app-name");
    expect(tauriCall.args[idx + 1]).toBeDefined();
    expect(await exists(join(tmp, "src-tauri/src/lib.rs"))).toBe(true);
  });
});
