import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseArchitectureSpec } from "@ori-ori/parser";
import eslintAdapter from "@ori-ori/arch-adapter-eslint";
import rustAdapter from "@ori-ori/arch-adapter-rust";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_ROOT = join(__dirname, "..", "ddd-typescript-tauri");

describe("ddd-typescript-tauri template", () => {
  it("includes a parsable multi-root .ori/architecture.md", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    expect(spec.version).toBe(1);
    expect(spec.default_root).toBe("ts");
    expect(spec.roots).toHaveLength(2);
    expect(spec.roots.map((r) => r.id).sort()).toEqual(["rs", "ts"]);
    expect(spec.cross_feature.prohibited_direct).toBe(true);
    expect(spec.cross_root).toHaveLength(1);
    expect(spec.cross_root[0]?.generator).toBe("tauri-specta");
  });

  it("ts root produces an eslint config with the FSD UI layers", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    const tsRoot = spec.roots.find((r) => r.id === "ts");
    expect(tsRoot).toBeDefined();
    const result = await eslintAdapter.export(spec, tsRoot!);
    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.path).toBe("eslint.config.ori.js");
    const content = result.files[0]!.content;
    for (const id of ["ui-entity", "ui-feature", "ui-widget", "ui-page"]) {
      expect(content).toContain(`"pattern": "src/${id}/**"`);
    }
    expect(content).toContain("src/lib/*/**");
  });

  it("rs root produces a self-contained tests/arch.rs", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    const rsRoot = spec.roots.find((r) => r.id === "rs");
    expect(rsRoot).toBeDefined();
    const result = await rustAdapter.export(spec, rsRoot!);
    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.path).toBe("src-tauri/tests/arch.rs");
    const content = result.files[0]!.content;
    expect(content).toContain("AUTO-GENERATED by @ori-ori/arch-adapter-rust");
    expect(content).toContain('const ROOT_PATH: &str = "src-tauri/src"');
    expect(content).toContain('const FEATURE_BASE: &str = "src-tauri/src/features/"');
    expect(content).toContain('("features", &["shared"])');
  });

  it("each adapter skips the other language root with a note", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    const tsRoot = spec.roots.find((r) => r.id === "ts")!;
    const rsRoot = spec.roots.find((r) => r.id === "rs")!;

    const rustOnTs = await rustAdapter.export(spec, tsRoot);
    expect(rustOnTs.files).toHaveLength(0);
    expect((rustOnTs.notes ?? []).join("\n")).toMatch(/skipped/);

    const eslintOnRs = await eslintAdapter.export(spec, rsRoot);
    expect(eslintOnRs.files).toHaveLength(0);
    expect((eslintOnRs.notes ?? []).join("\n")).toMatch(/skipped/);
  });

  it("ships the bindings-check CI workflow + pnpm script", async () => {
    const workflow = await readFile(
      join(TEMPLATE_ROOT, ".github/workflows/bindings-check.yml"),
      "utf8",
    );
    expect(workflow).toContain("tauri build --debug --no-bundle");
    expect(workflow).toContain("git diff --exit-code src/lib/shared/ipc/bindings.ts");

    const pkg = JSON.parse(
      await readFile(join(TEMPLATE_ROOT, "package.json"), "utf8"),
    );
    expect(pkg.scripts["bindings:check"]).toBeDefined();
    expect(pkg.scripts["bindings:check"]).toMatch(
      /git diff --exit-code src\/lib\/shared\/ipc\/bindings\.ts/,
    );
  });

  it("ships AI-agent instructions at the project root", async () => {
    const claude = await readFile(join(TEMPLATE_ROOT, "CLAUDE.md"), "utf8");
    const agents = await readFile(join(TEMPLATE_ROOT, "AGENTS.md"), "utf8");

    // Each file must cover the four headline rules so an AI agent reading
    // *either* file has the context it needs:
    //   1. feature-sliced layout (TS + Rust mirror)
    //   2. no-raw-invoke (use lib/shared/ipc/*)
    //   3. bindings regeneration tempo (pnpm tauri dev)
    //   4. feature-internal layering one-way rule
    for (const body of [claude, agents]) {
      expect(body).toMatch(/feature-?sliced|FSD/i);
      expect(body).toMatch(/@tauri-apps\/api\/core/);
      expect(body).toMatch(/lib\/shared\/ipc/);
      expect(body).toMatch(/tauri dev/);
      expect(body).toMatch(/presentation.*application.*domain|one-way/i);
      expect(body).toMatch(/\.ori\/architecture\.md/);
    }
  });

  it("ships the canonical TS scaffolding files", async () => {
    const expected = [
      "README.md",
      "CLAUDE.md",
      "AGENTS.md",
      "package.json",
      "tsconfig.json",
      "vitest.config.ts",
      "eslint.config.js",
      ".ori/architecture.md",
      "src/lib/shared/types/result.ts",
      "src/lib/shared/events/event.ts",
      "src/lib/shared/contracts/index.ts",
      "src/lib/shared/ipc/bindings.ts",
      "src/lib/shared/ipc/index.ts",
      "src/lib/tasks/index.ts",
      "src/lib/tasks/domain/task.ts",
      "src/lib/tasks/domain/task-id.ts",
      "src/lib/tasks/domain/task-title.ts",
      "src/lib/tasks/domain/events.ts",
      "src/lib/tasks/tests/task.test.ts",
      "src/ui-entity/task-card/index.ts",
      "src/ui-feature/complete-task/index.ts",
      "src/ui-widget/task-list/index.ts",
      "src/ui-page/tasks/index.ts",
      "src/__tests__/ui-flow.test.ts",
    ];
    for (const rel of expected) {
      await expect(readFile(join(TEMPLATE_ROOT, rel), "utf8")).resolves.toBeTypeOf("string");
    }
  });

  it("ships the ori Rust overlay (Tauri-owned files are delegated to 'tauri init')", async () => {
    const overlay = [
      "src-tauri/src/lib.rs",
      "src-tauri/src/features/mod.rs",
      "src-tauri/src/features/shared/mod.rs",
      "src-tauri/src/features/shared/result.rs",
      "src-tauri/src/features/shared/events.rs",
      "src-tauri/src/features/tasks/mod.rs",
      "src-tauri/src/features/tasks/domain.rs",
      "src-tauri/src/features/tasks/application.rs",
      "src-tauri/src/features/tasks/infrastructure.rs",
      "src-tauri/src/features/tasks/commands.rs",
    ];
    for (const rel of overlay) {
      await expect(readFile(join(TEMPLATE_ROOT, rel), "utf8")).resolves.toBeTypeOf("string");
    }

    // Tauri-owned, version-volatile files are *intentionally* absent; 'ori init
    // --template ddd-typescript-tauri' shells out to 'pnpm tauri init --ci ...'
    // to generate them, so they stay current with each Tauri release.
    const delegated = [
      "src-tauri/Cargo.toml",
      "src-tauri/build.rs",
      "src-tauri/tauri.conf.json",
      "src-tauri/capabilities/default.json",
      "src-tauri/src/main.rs",
    ];
    for (const rel of delegated) {
      await expect(readFile(join(TEMPLATE_ROOT, rel), "utf8")).rejects.toThrow();
    }
  });

  it("rust feature internals use idiomatic super:: imports", async () => {
    // arch-adapter-rust correctly resolves super:: for both mod.rs and
    // non-mod.rs siblings (fixed in ori-w5j), so feature-internal code
    // can rely on Rust's standard module-relative paths.
    const application = await readFile(
      join(TEMPLATE_ROOT, "src-tauri/src/features/tasks/application.rs"),
      "utf8",
    );
    expect(application).toMatch(/^use super::domain::/m);
    expect(application).toMatch(/^use super::infrastructure::/m);
  });
});
