import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { parseArchitectureSpec } from "@ori-ori/parser";
import eslintAdapter from "@ori-ori/arch-adapter-eslint";
import rustAdapter from "@ori-ori/arch-adapter-rust";

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_ROOT = join(__dirname, "..", "ddd-vsa-hex-typescript-tauri");

describe("ddd-vsa-hex-typescript-tauri template", () => {
  it("includes a parsable multi-root .ori/architecture.md", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    expect(spec.version).toBe(1);
    expect(spec.default_root).toBe("ts");
    expect(spec.roots).toHaveLength(2);
    expect(spec.roots.map((r) => r.id).sort()).toEqual(["rs", "ts"]);
    expect(spec.cross_slice.prohibited_direct).toBe(true);
    expect(spec.cross_root).toHaveLength(1);
    expect(spec.cross_root[0]?.generator).toBe("tauri-specta");
    // Both roots now share the same BC layout (slice_subdir = slices).
    const ts = spec.roots.find((r) => r.id === "ts")!;
    const rs = spec.roots.find((r) => r.id === "rs")!;
    expect(ts.slice_root).toBe("task-management");
    expect(ts.slice_subdir).toBe("slices");
    expect(rs.slice_root).toBe("task_management");
    expect(rs.slice_subdir).toBe("slices");
  });

  it("ts root produces an eslint config with the ddd-vsa-hex UI layers", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    const tsRoot = spec.roots.find((r) => r.id === "ts");
    expect(tsRoot).toBeDefined();
    const result = await eslintAdapter.export(spec, tsRoot!);
    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.path).toBe("eslint.config.ori.js");
    const content = result.files[0]!.content;
    // ddd-vsa-hex-ts keeps only ui-widget and ui-page.
    expect(content).toContain('"pattern": "apps/template-app/src/ui-widget/**"');
    expect(content).toContain('"pattern": "apps/template-app/src/ui-page/**"');
    expect(content).not.toContain("ui-entity");
    expect(content).not.toContain("ui-feature");
    // Slice pattern descends through slices/ subdir.
    expect(content).toContain("apps/template-app/src/task-management/slices/*/**");
  });

  it("rs root produces a self-contained tests/arch.rs", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    const rsRoot = spec.roots.find((r) => r.id === "rs");
    expect(rsRoot).toBeDefined();
    const result = await rustAdapter.export(spec, rsRoot!);
    expect(result.files).toHaveLength(1);
    expect(result.files[0]?.path).toBe("apps/template-app/src-tauri/tests/arch.rs");
    const content = result.files[0]!.content;
    expect(content).toContain("AUTO-GENERATED by @ori-ori/arch-adapter-rust");
    expect(content).toContain(
      'const ROOT_PATH: &str = "apps/template-app/src-tauri/src"',
    );
    expect(content).toContain(
      'const SLICE_BASE: &str = "apps/template-app/src-tauri/src/task_management/"',
    );
    expect(content).toContain('("domain", &["shared"])');
  });

  it("each adapter skips the other language root with a note", async () => {
    const raw = await readFile(join(TEMPLATE_ROOT, ".ori/architecture.md"), "utf8");
    const spec = parseArchitectureSpec(raw);
    const tsRoot = spec.roots.find((r) => r.id === "ts")!;
    const rsRoot = spec.roots.find((r) => r.id === "rs")!;

    const rustOnTs = await rustAdapter.export(spec, tsRoot);
    expect(rustOnTs.files).toHaveLength(0);
    expect((rustOnTs.notes ?? []).join("\n")).toMatch(/skipped/);

    const eslintOnRs = await eslintAdapter.export(spec, rsRoot);
    expect(eslintOnRs.files).toHaveLength(0);
    expect((eslintOnRs.notes ?? []).join("\n")).toMatch(/skipped/);
  });

  it("ships the bindings-check CI workflow + pnpm script", async () => {
    const workflow = await readFile(
      join(TEMPLATE_ROOT, ".github/workflows/bindings-check.yml"),
      "utf8",
    );
    expect(workflow).toContain("tauri build --debug --no-bundle");
    expect(workflow).toContain(
      "git diff --exit-code apps/template-app/src/task-management/shared/ipc/bindings.ts",
    );

    const pkg = JSON.parse(
      await readFile(join(TEMPLATE_ROOT, "package.json"), "utf8"),
    );
    expect(pkg.scripts["bindings:check"]).toBeDefined();
    expect(pkg.scripts["bindings:check"]).toMatch(
      /git diff --exit-code apps\/template-app\/src\/task-management\/shared\/ipc\/bindings\.ts/,
    );
  });

  it("ships AI-agent instructions at the project root", async () => {
    const claude = await readFile(join(TEMPLATE_ROOT, "CLAUDE.md"), "utf8");
    const agents = await readFile(join(TEMPLATE_ROOT, "AGENTS.md"), "utf8");

    // Each file must cover the four headline rules so an AI agent reading
    // *either* file has the context it needs:
    //   1. ddd-vsa-hex layout (TS + Rust mirror)
    //   2. no-raw-invoke (use task-management/shared/ipc/*)
    //   3. bindings regeneration tempo (pnpm tauri dev)
    //   4. slice-internal layering one-way rule
    for (const body of [claude, agents]) {
      expect(body).toMatch(/ddd-?vsa-?hex|slice/i);
      expect(body).toMatch(/@tauri-apps\/api\/core/);
      expect(body).toMatch(/shared\/ipc/);
      expect(body).toMatch(/tauri dev/);
      expect(body).toMatch(/presentation.*application.*domain|one-way/i);
      expect(body).toMatch(/\.ori\/architecture\.md/);
    }
  });

  it("package.json devDependencies pin a runnable lint+typecheck baseline", async () => {
    const pkg = JSON.parse(
      await readFile(join(TEMPLATE_ROOT, "package.json"), "utf8"),
    );
    const deps = pkg.devDependencies ?? {};
    // ori-aw6 (tauri variant): same cli pin as the typescript template.
    expect(deps["@ori-ori/cli"]).toBe("^0.1.0");
    // ori-1ui (tauri variant): tsconfig requires @types/node.
    expect(deps["@types/node"]).toMatch(/^\^?\d/);
  });

  it("ships the canonical TS scaffolding files", async () => {
    const expected = [
      "README.md",
      "CLAUDE.md",
      "AGENTS.md",
      "package.json",
      "tsconfig.json",
      "vitest.config.ts",
      "eslint.config.js",
      ".ori/architecture.md",
      "apps/template-app/src/task-management/shared/types/result.ts",
      "apps/template-app/src/task-management/shared/events/event.ts",
      "apps/template-app/src/task-management/shared/contracts/index.ts",
      "apps/template-app/src/task-management/shared/ipc/bindings.ts",
      "apps/template-app/src/task-management/shared/ipc/index.ts",
      "apps/template-app/src/task-management/slices/complete-task/index.ts",
      "apps/template-app/src/task-management/slices/complete-task/domain/task.ts",
      "apps/template-app/src/task-management/slices/complete-task/domain/task-id.ts",
      "apps/template-app/src/task-management/slices/complete-task/domain/task-title.ts",
      "apps/template-app/src/task-management/slices/complete-task/domain/events.ts",
      "apps/template-app/src/task-management/slices/complete-task/application/complete-task.ts",
      "apps/template-app/src/task-management/slices/complete-task/presentation/task-card.ts",
      "apps/template-app/src/task-management/slices/complete-task/tests/task.test.ts",
      "apps/template-app/src/ui-widget/task-list/index.ts",
      "apps/template-app/src/ui-page/tasks/index.ts",
      "apps/template-app/src/__tests__/ui-flow.test.ts",
    ];
    for (const rel of expected) {
      await expect(readFile(join(TEMPLATE_ROOT, rel), "utf8")).resolves.toBeTypeOf("string");
    }
  });

  it("ships the ori Rust overlay (Tauri-owned files are delegated to 'tauri init')", async () => {
    const overlay = [
      "apps/template-app/src-tauri/src/lib.rs",
      "apps/template-app/src-tauri/src/task_management/mod.rs",
      "apps/template-app/src-tauri/src/task_management/shared/mod.rs",
      "apps/template-app/src-tauri/src/task_management/shared/result.rs",
      "apps/template-app/src-tauri/src/task_management/shared/events.rs",
      "apps/template-app/src-tauri/src/task_management/slices/mod.rs",
      "apps/template-app/src-tauri/src/task_management/slices/complete_task/mod.rs",
      "apps/template-app/src-tauri/src/task_management/slices/complete_task/domain.rs",
      "apps/template-app/src-tauri/src/task_management/slices/complete_task/application.rs",
      "apps/template-app/src-tauri/src/task_management/slices/complete_task/infrastructure.rs",
      "apps/template-app/src-tauri/src/task_management/slices/complete_task/commands.rs",
    ];
    for (const rel of overlay) {
      await expect(readFile(join(TEMPLATE_ROOT, rel), "utf8")).resolves.toBeTypeOf("string");
    }

    // Tauri-owned, version-volatile files are *intentionally* absent; 'ori init
    // --template ddd-vsa-hex-typescript-tauri' shells out to 'pnpm tauri init
    // --ci ...' to generate them, so they stay current with each Tauri release.
    const delegated = [
      "apps/template-app/src-tauri/Cargo.toml",
      "apps/template-app/src-tauri/build.rs",
      "apps/template-app/src-tauri/tauri.conf.json",
      "apps/template-app/src-tauri/capabilities/default.json",
      "apps/template-app/src-tauri/src/main.rs",
    ];
    for (const rel of delegated) {
      await expect(readFile(join(TEMPLATE_ROOT, rel), "utf8")).rejects.toThrow();
    }
  });

  it("rust slice internals use idiomatic super:: imports", async () => {
    // arch-adapter-rust correctly resolves super:: for both mod.rs and
    // non-mod.rs siblings (fixed in ori-w5j), so slice-internal code
    // can rely on Rust's standard module-relative paths.
    const application = await readFile(
      join(
        TEMPLATE_ROOT,
        "apps/template-app/src-tauri/src/task_management/slices/complete_task/application.rs",
      ),
      "utf8",
    );
    expect(application).toMatch(/^use super::domain::/m);
    expect(application).toMatch(/^use super::infrastructure::/m);
  });
});
